### ISSUE TITLE
Commitメッセージに関するの設定をローカル上で可能にする

### ISSUE THREAD

**Issue by cocoide** [cocoide/commitify#1]
viperというフレームワークを使用して、設定ファイルを作成、参照する。
https://github.com/spf13/viper

OpenAIのAPIのTokenを設定できるようにする
コマンドラインの設定をできるようにする

**Comment by mochi-yu** [comment]
- [ ] OpenAIのAPIキーを登録できる
- [ ] OpenAIのAPIキーを参照できる
